[2024-06-18T17:45:49.985+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T17:45:50.003+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T12:14:48.361642+00:00 [queued]>
[2024-06-18T17:45:50.014+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T12:14:48.361642+00:00 [queued]>
[2024-06-18T17:45:50.015+0530] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T17:45:50.036+0530] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 12:14:48.361642+00:00
[2024-06-18T17:45:50.038+0530] {standard_task_runner.py:63} INFO - Started process 38109 to run task
[2024-06-18T17:45:50.041+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'manual__2024-06-18T12:14:48.361642+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmpmypawuhh']
[2024-06-18T17:45:50.044+0530] {standard_task_runner.py:91} INFO - Job 69: Subtask backup_task
[2024-06-18T17:45:50.096+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task manual__2024-06-18T12:14:48.361642+00:00 [running]> on host FN-21052948.
[2024-06-18T17:45:50.180+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T12:14:48.361642+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T12:14:48.361642+00:00'
[2024-06-18T17:45:50.181+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T17:45:50.188+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T17:45:50.189+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/kiit/airflow/bashScripts/backup.sh ']
[2024-06-18T17:45:50.196+0530] {subprocess.py:86} INFO - Output:
[2024-06-18T17:45:50.203+0530] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T17:45:50.204+0530] {subprocess.py:93} INFO - ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (13)
[2024-06-18T17:45:50.205+0530] {subprocess.py:93} INFO - Error: Unable to connect to MySQL server.
[2024-06-18T17:45:50.205+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-18T17:45:50.205+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T17:45:50.215+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-18T17:45:50.218+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=backup_task, run_id=manual__2024-06-18T12:14:48.361642+00:00, execution_date=20240618T121448, start_date=20240618T121550, end_date=20240618T121550
[2024-06-18T17:45:50.239+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 69 for task backup_task (Bash command failed. The command returned a non-zero exit code 1.; 38109)
[2024-06-18T17:45:50.254+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T17:45:50.277+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T17:45:50.292+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
