[2024-06-19T09:41:04.968+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T09:41:04.986+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:00:00+00:00 [queued]>
[2024-06-19T09:41:04.993+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:00:00+00:00 [queued]>
[2024-06-19T09:41:04.994+0530] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-19T09:41:05.012+0530] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 04:00:00+00:00
[2024-06-19T09:41:05.014+0530] {standard_task_runner.py:63} INFO - Started process 2331 to run task
[2024-06-19T09:41:05.018+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T04:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmp48rt7vqy']
[2024-06-19T09:41:05.020+0530] {standard_task_runner.py:91} INFO - Job 87: Subtask send_mail
[2024-06-19T09:41:05.069+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:00:00+00:00 [running]> on host FN-21052948.
[2024-06-19T09:41:05.151+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T04:00:00+00:00'
[2024-06-19T09:41:05.152+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T09:41:05.174+0530] {logging_mixin.py:188} WARNING - /home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T09:41:05.174+0530] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T09:41:05.174+0530] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T09:41:06.597+0530] {email.py:282} INFO - Sent an alert email to ['neupanesarika17@gmail.com']
[2024-06-19T09:41:07.470+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T09:41:07.471+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/lib/python3.8/smtplib.py", line 880, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855e5613esm105621575ad.15 - gsmtp', 'neupanesarika17@gmail.com')
[2024-06-19T09:41:07.480+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T04:00:00+00:00, execution_date=20240619T040000, start_date=20240619T041104, end_date=20240619T041107
[2024-06-19T09:41:07.498+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 87 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855e5613esm105621575ad.15 - gsmtp', 'neupanesarika17@gmail.com'); 2331)
[2024-06-19T09:41:07.530+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T09:41:07.541+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
