[2024-06-18T16:32:42.601+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T16:32:42.619+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T11:02:41.619855+00:00 [queued]>
[2024-06-18T16:32:42.627+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T11:02:41.619855+00:00 [queued]>
[2024-06-18T16:32:42.627+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T16:32:42.646+0530] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 11:02:41.619855+00:00
[2024-06-18T16:32:42.648+0530] {standard_task_runner.py:63} INFO - Started process 36856 to run task
[2024-06-18T16:32:42.651+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'manual__2024-06-18T11:02:41.619855+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmphe6rpb3e']
[2024-06-18T16:32:42.652+0530] {standard_task_runner.py:91} INFO - Job 43: Subtask backup_task
[2024-06-18T16:32:42.701+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task manual__2024-06-18T11:02:41.619855+00:00 [running]> on host FN-21052948.
[2024-06-18T16:32:42.779+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T11:02:41.619855+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T11:02:41.619855+00:00'
[2024-06-18T16:32:42.779+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T16:32:42.789+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T16:32:42.789+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/kiit/airflow/bashScripts/backup.sh ']
[2024-06-18T16:32:42.798+0530] {subprocess.py:86} INFO - Output:
[2024-06-18T16:32:42.798+0530] {subprocess.py:93} INFO - /home/kiit/airflow/bashScripts/backup.sh: line 71: /home/kiit/airflow/bashscripts/delete.sh: No such file or directory
[2024-06-18T16:32:42.803+0530] {subprocess.py:93} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T16:32:42.804+0530] {subprocess.py:93} INFO - ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (13)
[2024-06-18T16:32:42.806+0530] {subprocess.py:93} INFO - (standard_in) 1: syntax error
[2024-06-18T16:32:42.810+0530] {subprocess.py:93} INFO - df: /mnt/c: Input/output error
[2024-06-18T16:32:42.810+0530] {subprocess.py:93} INFO - df: /Docker/host: Input/output error
[2024-06-18T16:32:42.814+0530] {subprocess.py:93} INFO - (standard_in) 1: syntax error
[2024-06-18T16:32:42.814+0530] {subprocess.py:93} INFO - /home/kiit/airflow/bashScripts/backup.sh: line 98: [: -eq: unary operator expected
[2024-06-18T16:32:42.814+0530] {subprocess.py:93} INFO - Backup Failed.|Required Space: GB, Available Space: 2529.40GB
[2024-06-18T16:32:42.814+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T16:32:42.815+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T16:32:42.849+0530] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=manual__2024-06-18T11:02:41.619855+00:00, execution_date=20240618T110241, start_date=20240618T110242, end_date=20240618T110242
[2024-06-18T16:32:42.905+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T16:32:42.926+0530] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T16:32:42.933+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
