[2024-06-19T10:20:02.062+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T10:20:02.077+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:40:00+00:00 [queued]>
[2024-06-19T10:20:02.083+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:40:00+00:00 [queued]>
[2024-06-19T10:20:02.083+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T10:20:02.099+0530] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 04:40:00+00:00
[2024-06-19T10:20:02.101+0530] {standard_task_runner.py:63} INFO - Started process 4189 to run task
[2024-06-19T10:20:02.104+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T04:40:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmpl3pyfjqn']
[2024-06-19T10:20:02.105+0530] {standard_task_runner.py:91} INFO - Job 121: Subtask send_mail
[2024-06-19T10:20:02.144+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:40:00+00:00 [running]> on host FN-21052948.
[2024-06-19T10:20:02.214+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T04:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T04:40:00+00:00'
[2024-06-19T10:20:02.215+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T10:20:02.233+0530] {logging_mixin.py:188} WARNING - /home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T10:20:02.234+0530] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T10:20:02.234+0530] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T10:20:03.348+0530] {email.py:282} INFO - Sent an alert email to ['neupanesarika17@gmail.com']
[2024-06-19T10:20:04.249+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T10:20:04.250+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/lib/python3.8/smtplib.py", line 880, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855f1a1ebsm106420755ad.238 - gsmtp', 'neupanesarika17@gmail.com')
[2024-06-19T10:20:04.266+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T04:40:00+00:00, execution_date=20240619T044000, start_date=20240619T045002, end_date=20240619T045004
[2024-06-19T10:20:04.286+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 121 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855f1a1ebsm106420755ad.238 - gsmtp', 'neupanesarika17@gmail.com'); 4189)
[2024-06-19T10:20:04.327+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T10:20:04.344+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T10:20:04.345+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-19T10:24:28.376+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T10:24:28.394+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:40:00+00:00 [queued]>
[2024-06-19T10:24:28.400+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:40:00+00:00 [queued]>
[2024-06-19T10:24:28.400+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T10:24:28.418+0530] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 04:40:00+00:00
[2024-06-19T10:24:28.422+0530] {standard_task_runner.py:63} INFO - Started process 4672 to run task
[2024-06-19T10:24:28.424+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T04:40:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmpblyigfxa']
[2024-06-19T10:24:28.426+0530] {standard_task_runner.py:91} INFO - Job 126: Subtask send_mail
[2024-06-19T10:24:28.479+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:40:00+00:00 [running]> on host FN-21052948.
[2024-06-19T10:24:28.590+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T04:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T04:40:00+00:00'
[2024-06-19T10:24:28.591+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T10:24:28.626+0530] {logging_mixin.py:188} WARNING - /home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T10:24:28.627+0530] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T10:24:28.627+0530] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T10:24:29.729+0530] {email.py:282} INFO - Sent an alert email to ['neupanesarika17@gmail.com']
[2024-06-19T10:24:30.818+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T10:24:30.819+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/lib/python3.8/smtplib.py", line 880, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855f4aaecsm106312465ad.284 - gsmtp', 'neupanesarika17@gmail.com')
[2024-06-19T10:24:30.829+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T04:40:00+00:00, execution_date=20240619T044000, start_date=20240619T045428, end_date=20240619T045430
[2024-06-19T10:24:30.844+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 126 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d9443c01a7336-1f855f4aaecsm106312465ad.284 - gsmtp', 'neupanesarika17@gmail.com'); 4672)
[2024-06-19T10:24:30.851+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T10:24:30.866+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T10:24:30.868+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
