[2024-06-18T15:43:14.104+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T15:43:14.117+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T10:00:00+00:00 [queued]>
[2024-06-18T15:43:14.122+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T10:00:00+00:00 [queued]>
[2024-06-18T15:43:14.122+0530] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T15:43:14.136+0530] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 10:00:00+00:00
[2024-06-18T15:43:14.140+0530] {standard_task_runner.py:63} INFO - Started process 36046 to run task
[2024-06-18T15:43:14.144+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T10:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmp4_wviqih']
[2024-06-18T15:43:14.145+0530] {standard_task_runner.py:91} INFO - Job 24: Subtask backup_task
[2024-06-18T15:43:14.188+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T10:00:00+00:00 [running]> on host FN-21052948.
[2024-06-18T15:43:14.237+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T10:00:00+00:00'
[2024-06-18T15:43:14.238+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T15:43:14.245+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T15:43:14.245+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/kiit/airflow/bashScripts/backup.sh ']
[2024-06-18T15:43:14.250+0530] {subprocess.py:86} INFO - Output:
[2024-06-18T15:43:14.253+0530] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T15:43:14.255+0530] {subprocess.py:93} INFO - mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (13) when trying to connect
[2024-06-18T15:43:14.255+0530] {subprocess.py:97} INFO - Command exited with return code 2
[2024-06-18T15:43:14.255+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T15:43:14.262+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-06-18T15:43:14.265+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T10:00:00+00:00, execution_date=20240618T100000, start_date=20240618T101314, end_date=20240618T101314
[2024-06-18T15:43:14.277+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task backup_task (Bash command failed. The command returned a non-zero exit code 2.; 36046)
[2024-06-18T15:43:14.315+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T15:43:14.336+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T15:43:14.343+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
