[2024-06-19T09:53:13.241+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T09:53:13.260+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-19T04:23:10.969622+00:00 [queued]>
[2024-06-19T09:53:13.267+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-19T04:23:10.969622+00:00 [queued]>
[2024-06-19T09:53:13.267+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T09:53:13.284+0530] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 04:23:10.969622+00:00
[2024-06-19T09:53:13.286+0530] {standard_task_runner.py:63} INFO - Started process 2741 to run task
[2024-06-19T09:53:13.289+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'manual__2024-06-19T04:23:10.969622+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmpka2w2cuq']
[2024-06-19T09:53:13.291+0530] {standard_task_runner.py:91} INFO - Job 97: Subtask send_mail
[2024-06-19T09:53:13.333+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail manual__2024-06-19T04:23:10.969622+00:00 [running]> on host FN-21052948.
[2024-06-19T09:53:13.412+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T04:23:10.969622+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T04:23:10.969622+00:00'
[2024-06-19T09:53:13.413+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T09:53:13.432+0530] {logging_mixin.py:188} WARNING - /home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T09:53:13.432+0530] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T09:53:13.432+0530] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T09:53:14.450+0530] {email.py:282} INFO - Sent an alert email to ['neupanesarika17@gmail.com']
[2024-06-19T09:53:15.386+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T09:53:15.387+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/lib/python3.8/smtplib.py", line 880, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 98e67ed59e1d1-2c7a2ae3f36sm1764326a91.13 - gsmtp', 'neupanesarika17@gmail.com')
[2024-06-19T09:53:15.398+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Backup_Database, task_id=send_mail, run_id=manual__2024-06-19T04:23:10.969622+00:00, execution_date=20240619T042310, start_date=20240619T042313, end_date=20240619T042315
[2024-06-19T09:53:15.416+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 97 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 98e67ed59e1d1-2c7a2ae3f36sm1764326a91.13 - gsmtp', 'neupanesarika17@gmail.com'); 2741)
[2024-06-19T09:53:15.436+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T09:53:15.450+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T09:53:15.451+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
