[2024-06-19T09:51:04.669+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T09:51:04.685+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:10:00+00:00 [queued]>
[2024-06-19T09:51:04.692+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:10:00+00:00 [queued]>
[2024-06-19T09:51:04.692+0530] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-19T09:51:04.711+0530] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 04:10:00+00:00
[2024-06-19T09:51:04.713+0530] {standard_task_runner.py:63} INFO - Started process 2622 to run task
[2024-06-19T09:51:04.716+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T04:10:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmpffhpeznj']
[2024-06-19T09:51:04.718+0530] {standard_task_runner.py:91} INFO - Job 91: Subtask send_mail
[2024-06-19T09:51:04.765+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:10:00+00:00 [running]> on host FN-21052948.
[2024-06-19T09:51:04.838+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T04:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T04:10:00+00:00'
[2024-06-19T09:51:04.838+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T09:51:04.859+0530] {logging_mixin.py:188} WARNING - /home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T09:51:04.860+0530] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T09:51:04.860+0530] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T09:51:05.892+0530] {email.py:282} INFO - Sent an alert email to ['neupanesarika17@gmail.com']
[2024-06-19T09:51:06.766+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T09:51:06.767+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/lib/python3.8/smtplib.py", line 880, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 98e67ed59e1d1-2c4c45abaccsm11855547a91.9 - gsmtp', 'neupanesarika17@gmail.com')
[2024-06-19T09:51:06.779+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T04:10:00+00:00, execution_date=20240619T041000, start_date=20240619T042104, end_date=20240619T042106
[2024-06-19T09:51:06.794+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 91 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 98e67ed59e1d1-2c4c45abaccsm11855547a91.9 - gsmtp', 'neupanesarika17@gmail.com'); 2622)
[2024-06-19T09:51:06.823+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T09:51:06.841+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T09:51:06.842+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-19T09:54:10.593+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T09:54:10.611+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:10:00+00:00 [queued]>
[2024-06-19T09:54:10.620+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:10:00+00:00 [queued]>
[2024-06-19T09:54:10.620+0530] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-19T09:54:10.635+0530] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-19 04:10:00+00:00
[2024-06-19T09:54:10.637+0530] {standard_task_runner.py:63} INFO - Started process 2763 to run task
[2024-06-19T09:54:10.640+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-19T04:10:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/basic.py', '--cfg-path', '/tmp/tmpfk_sbv7e']
[2024-06-19T09:54:10.642+0530] {standard_task_runner.py:91} INFO - Job 98: Subtask send_mail
[2024-06-19T09:54:10.691+0530] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-19T04:10:00+00:00 [running]> on host FN-21052948.
[2024-06-19T09:54:10.771+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarika' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T04:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T04:10:00+00:00'
[2024-06-19T09:54:10.772+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T09:54:10.792+0530] {logging_mixin.py:188} WARNING - /home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-19T09:54:10.792+0530] {configuration.py:1050} WARNING - section/key [smtp/smtp_password] not found in config
[2024-06-19T09:54:10.792+0530] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T09:54:11.854+0530] {email.py:282} INFO - Sent an alert email to ['neupanesarika17@gmail.com']
[2024-06-19T09:54:12.774+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T09:54:12.774+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/kiit/airflow-env/lib/python3.8/site-packages/airflow/utils/email.py", line 283, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/lib/python3.8/smtplib.py", line 880, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d2e1a72fcca58-705ccb72555sm9766809b3a.181 - gsmtp', 'neupanesarika17@gmail.com')
[2024-06-19T09:54:12.784+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-19T04:10:00+00:00, execution_date=20240619T041000, start_date=20240619T042410, end_date=20240619T042412
[2024-06-19T09:54:12.820+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 98 for task send_mail ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError d2e1a72fcca58-705ccb72555sm9766809b3a.181 - gsmtp', 'neupanesarika17@gmail.com'); 2763)
[2024-06-19T09:54:12.827+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T09:54:12.841+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T09:54:12.842+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
